---
- name: Ensure SSH daemon is running
  service:
    name: "{{ hardening_server_name }}"
    state: "{{ hardening_sshd_state }}"

- name: Use custom hardened sshd_config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/hardened.conf
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
  notify: restart ssh
